apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    run: tomcat
spec:
  type: NodePort
  ports:
  - port: 9000 
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: tomcat
